// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoaVAhdLP56_6YpABzrLnQlARjjU84b7M',
    appId: '1:644942500262:web:ffc70875d0ce759128ff67',
    messagingSenderId: '644942500262',
    projectId: 'backtesting-1a89a',
    authDomain: 'backtesting-1a89a.firebaseapp.com',
    storageBucket: 'backtesting-1a89a.firebasestorage.app',
    measurementId: 'G-8W4YJL7JSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyiqWL_3H-keVJPxcopqIn5V_RAWcaADA',
    appId: '1:644942500262:android:4a117bf81bc56a2428ff67',
    messagingSenderId: '644942500262',
    projectId: 'backtesting-1a89a',
    storageBucket: 'backtesting-1a89a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm8yjpNk4xq3x7Hip487I-gndZPFUQx_o',
    appId: '1:644942500262:ios:3ae0d9465ce9af3328ff67',
    messagingSenderId: '644942500262',
    projectId: 'backtesting-1a89a',
    storageBucket: 'backtesting-1a89a.firebasestorage.app',
    iosBundleId: 'com.example.backtesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm8yjpNk4xq3x7Hip487I-gndZPFUQx_o',
    appId: '1:644942500262:ios:3ae0d9465ce9af3328ff67',
    messagingSenderId: '644942500262',
    projectId: 'backtesting-1a89a',
    storageBucket: 'backtesting-1a89a.firebasestorage.app',
    iosBundleId: 'com.example.backtesting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoaVAhdLP56_6YpABzrLnQlARjjU84b7M',
    appId: '1:644942500262:web:9dd910dadecf494028ff67',
    messagingSenderId: '644942500262',
    projectId: 'backtesting-1a89a',
    authDomain: 'backtesting-1a89a.firebaseapp.com',
    storageBucket: 'backtesting-1a89a.firebasestorage.app',
    measurementId: 'G-BNHZCXKCW9',
  );
}
